### ISSUE TITLE
University site redirection is not correct!

### ISSUE THREAD

**Issue by BaseMax** [yoosofan/src_website#2]
Hello;

It seems the university site does not have the correct redirection config.

For example:
- `http://yoosofan.kashanu.ac.ir/` => `http://yoosofan.github.io/`
- `http://yoosofan.kashanu.ac.ir/123`=> `http://yoosofan.github.io123/`
- `http://yoosofan.kashanu.ac.ir/bar/foo` => `http://yoosofan.github.iobar/foo`

**Comment by yoosofan** [comment]
Yes, it does not, I did not have time to change that in the kashanu
